name: Build WPF Cybersecurity Chatbot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build WPF Application
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # or '7.0.x' depending on your project version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release

    - name: Run tests (if any)
      run: dotnet test --no-build --verbosity normal
      continue-on-error: true  # Remove this if you want tests to fail the workflow
